baseURL = '/'
languageCode = 'en-us'
title = 'Folio'
theme = 'archie'
copyright = "Rohan Shetty"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/rohaen-shetty"
    twitter = "https://twitter.com/rohaen-shetty"
    email = "hanshetty641@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"